/* eslint-disable */
/**
 * 台州供水项目
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface AddListParameterConfigInput
 */
export interface AddListParameterConfigInput {
    /**
     *
     * @type {string}
     * @memberof AddListParameterConfigInput
     */
    deviceId?: string
    /**
     * 设备名称
     * @type {string}
     * @memberof AddListParameterConfigInput
     */
    deviceName?: string | null
    /**
     * 综合费用（吨耗）
     * @type {number}
     * @memberof AddListParameterConfigInput
     */
    omnibusFee?: number
    /**
     * 最大规模（万m3/d）
     * @type {number}
     * @memberof AddListParameterConfigInput
     */
    max?: number
    /**
     * 最小规模（万m3/d）
     * @type {number}
     * @memberof AddListParameterConfigInput
     */
    min?: number
}
