/* eslint-disable */
/**
 * 台州供水项目
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { FenQiFlowInfo } from './fen-qi-flow-info'
// May contain unused imports in some cases
// @ts-ignore
import { GroupFlowInfo } from './group-flow-info'
// May contain unused imports in some cases
// @ts-ignore
import { TankOpenOrCloseEditDto } from './tank-open-or-close-edit-dto'

/**
 *
 * @export
 * @interface AllocationEditDto
 */
export interface AllocationEditDto {
    /**
     * 调配流量编辑数据
     * @type {Array<GroupFlowInfo>}
     * @memberof AllocationEditDto
     */
    flowSchedules?: Array<GroupFlowInfo> | null
    /**
     * 分期水量编辑数据
     * @type {Array<FenQiFlowInfo>}
     * @memberof AllocationEditDto
     */
    fenQiFlowList?: Array<FenQiFlowInfo> | null
    /**
     * 编辑的补充水量，二期减去补充水量，三四期加上补充水量
     * @type {number}
     * @memberof AllocationEditDto
     */
    editSupplyFlow?: number
    /**
     * 实测补充水量
     * @type {number}
     * @memberof AllocationEditDto
     */
    srcSupplyFlow?: number
    /**
     * 水库编辑数据
     * @type {Array<TankOpenOrCloseEditDto>}
     * @memberof AllocationEditDto
     */
    tankOpenOrCloseEditInfos?: Array<TankOpenOrCloseEditDto> | null
}
