/* eslint-disable */
/**
 * 台州供水项目
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ComputeOutput
 */
export interface ComputeOutput {
    /**
     *
     * @type {boolean}
     * @memberof ComputeOutput
     */
    hasError?: boolean
    /**
     *
     * @type {string}
     * @memberof ComputeOutput
     */
    queueId?: string
    /**
     *
     * @type {string}
     * @memberof ComputeOutput
     */
    message?: string | null
    /**
     *
     * @type {string}
     * @memberof ComputeOutput
     */
    scenarioId?: string
}
