/* tslint:disable */
/* eslint-disable */
/**
 * 城市供水业务中台
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { FenQiFlowInfo1 } from './fen-qi-flow-info1'
// May contain unused imports in some cases
// @ts-ignore
import { GroupFlowInfo1 } from './group-flow-info1'
// May contain unused imports in some cases
// @ts-ignore
import { ScenarioInfo3 } from './scenario-info3'
// May contain unused imports in some cases
// @ts-ignore
import { TankOpenOrCloseEditDto } from './tank-open-or-close-edit-dto'

/**
 *
 * @export
 * @interface ComputeInput1
 */
export interface ComputeInput1 {
    /**
     * 调配流量编辑数据
     * @type {Array<GroupFlowInfo1>}
     * @memberof ComputeInput1
     */
    flowSchedules?: Array<GroupFlowInfo1> | null
    /**
     * 分期水量编辑数据
     * @type {Array<FenQiFlowInfo1>}
     * @memberof ComputeInput1
     */
    fenQiFlowList?: Array<FenQiFlowInfo1> | null
    /**
     * 编辑的补充水量，二期减去补充水量，三四期加上补充水量
     * @type {number}
     * @memberof ComputeInput1
     */
    editSupplyFlow?: number
    /**
     * 实测补充水量
     * @type {number}
     * @memberof ComputeInput1
     */
    srcSupplyFlow?: number
    /**
     * 水库编辑数据
     * @type {Array<TankOpenOrCloseEditDto>}
     * @memberof ComputeInput1
     */
    tankOpenOrCloseEditInfos?: Array<TankOpenOrCloseEditDto> | null
    /**
     *
     * @type {ScenarioInfo3}
     * @memberof ComputeInput1
     */
    scenario?: ScenarioInfo3
}
