/* eslint-disable */
/**
 * 城市供水业务中台
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ComputeOutput1
 */
export interface ComputeOutput1 {
    /**
     *
     * @type {boolean}
     * @memberof ComputeOutput1
     */
    hasError?: boolean
    /**
     *
     * @type {string}
     * @memberof ComputeOutput1
     */
    queueId?: string
    /**
     *
     * @type {string}
     * @memberof ComputeOutput1
     */
    message?: string | null
    /**
     *
     * @type {string}
     * @memberof ComputeOutput1
     */
    scenarioId?: string
}
