/* eslint-disable */
/**
 * 台州供水项目
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 获取预测日调配水量
 * @export
 * @interface DailyFlowInfo
 */
export interface DailyFlowInfo {
    /**
     * 分组名称
     * @type {string}
     * @memberof DailyFlowInfo
     */
    groupName?: string | null
    /**
     * 预测日调配水量
     * @type {number}
     * @memberof DailyFlowInfo
     */
    forecastValue?: number
    /**
     * 当前累计调配水量
     * @type {number}
     * @memberof DailyFlowInfo
     */
    currentValue?: number
}
