/* eslint-disable */
/**
 * 台州供水项目
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface FenQiFlowInfo
 */
export interface FenQiFlowInfo {
    /**
     * 分组id
     * @type {string}
     * @memberof FenQiFlowInfo
     */
    groupId?: string | null
    /**
     * 分组名称
     * @type {string}
     * @memberof FenQiFlowInfo
     */
    groupName?: string | null
    /**
     * 分组关联的设备id列表
     * @type {Array<string>}
     * @memberof FenQiFlowInfo
     */
    deviceIds?: Array<string> | null
    /**
     * 允许最大输水量（万m3/d）
     * @type {number}
     * @memberof FenQiFlowInfo
     */
    maxFlow?: number
    /**
     * 调配水量（万m3/d）
     * @type {number}
     * @memberof FenQiFlowInfo
     */
    allocFlow?: number
}
