/* tslint:disable */
/* eslint-disable */
/**
 * 城市供水业务中台
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface FlowDetail1
 */
export interface FlowDetail1 {
    /**
     * 设备id
     * @type {string}
     * @memberof FlowDetail1
     */
    deviceId?: string
    /**
     * 设备名称
     * @type {string}
     * @memberof FlowDetail1
     */
    deviceName?: string | null
    /**
     * 水量
     * @type {number}
     * @memberof FlowDetail1
     */
    flow?: number
    /**
     * 0:数据正常 1:数据缺失 2:数据异常
     * @type {number}
     * @memberof FlowDetail1
     */
    tag?: number
    /**
     * 实测流量提示信息（缺失或异常情况下有提示信息）
     * @type {string}
     * @memberof FlowDetail1
     */
    tipMessage?: string | null
}
