/* tslint:disable */
/* eslint-disable */
/**
 * 城市供水业务中台
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { ScenarioScheduleDevice } from './scenario-schedule-device'

/**
 *
 * @export
 * @interface GetScenarioScheduleFlowInput
 */
export interface GetScenarioScheduleFlowInput {
    /**
     * 日期
     * @type {string}
     * @memberof GetScenarioScheduleFlowInput
     */
    dateTime?: string
    /**
     * 调度预案编辑设备列表(包含设备指标信息)
     * @type {Array<ScenarioScheduleDevice>}
     * @memberof GetScenarioScheduleFlowInput
     */
    scenarioScheduleDevices?: Array<ScenarioScheduleDevice> | null
}
