/* eslint-disable */
/**
 * 台州供水项目
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { GroupFlowInfo } from './group-flow-info'

/**
 *
 * @export
 * @interface GetFenQiFlowByEditInput
 */
export interface GetFenQiFlowByEditInput {
    /**
     * 编辑的补充水量
     * @type {number}
     * @memberof GetFenQiFlowByEditInput
     */
    editSupplyFlow?: number
    /**
     * 片区水量
     * @type {Array<GroupFlowInfo>}
     * @memberof GetFenQiFlowByEditInput
     */
    flowSchedules: Array<GroupFlowInfo>
}
