/* tslint:disable */
/* eslint-disable */
/**
 * 城市供水业务中台
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { ScenarioEditFlow } from './scenario-edit-flow'

/**
 *
 * @export
 * @interface GetScenarioFenQiFlowInput
 */
export interface GetScenarioFenQiFlowInput {
    /**
     * 日期
     * @type {string}
     * @memberof GetScenarioFenQiFlowInput
     */
    dateTime?: string
    /**
     * 编辑后的补充水量
     * @type {number}
     * @memberof GetScenarioFenQiFlowInput
     */
    editSupplyFlow?: number
    /**
     * 编辑后的设备调配水量
     * @type {Array<ScenarioEditFlow>}
     * @memberof GetScenarioFenQiFlowInput
     */
    scenarioEditFlow: Array<ScenarioEditFlow>
    /**
     * 长谭水库平均液位（如果界面有编辑，则传递编辑后的数据）
     * @type {number}
     * @memberof GetScenarioFenQiFlowInput
     */
    changTanEditLevel?: number
}
