/* tslint:disable */
/* eslint-disable */
/**
 * 城市供水业务中台
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { FlowDetail1 } from './flow-detail1'

/**
 *
 * @export
 * @interface GroupFlowInfo1
 */
export interface GroupFlowInfo1 {
    /**
     * 分组id
     * @type {string}
     * @memberof GroupFlowInfo1
     */
    groupId?: string | null
    /**
     * 分组名称
     * @type {string}
     * @memberof GroupFlowInfo1
     */
    groupName?: string | null
    /**
     * 流量详情
     * @type {Array<FlowDetail1>}
     * @memberof GroupFlowInfo1
     */
    flowDetail?: Array<FlowDetail1> | null
}
