/* eslint-disable */
/**
 * 台州供水项目
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { FlowDetail } from './flow-detail'

/**
 *
 * @export
 * @interface GroupFlowInfo
 */
export interface GroupFlowInfo {
    /**
     * 分组id
     * @type {string}
     * @memberof GroupFlowInfo
     */
    groupId?: string | null
    /**
     * 分组名称
     * @type {string}
     * @memberof GroupFlowInfo
     */
    groupName?: string | null
    /**
     * 流量详情
     * @type {Array<FlowDetail>}
     * @memberof GroupFlowInfo
     */
    flowDetail?: Array<FlowDetail> | null
}
