/* tslint:disable */
/* eslint-disable */
/**
 * 城市供水业务中台
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { OnlineData } from './online-data'

/**
 *
 * @export
 * @interface ScenarioScheduleEditFlow
 */
export interface ScenarioScheduleEditFlow {
    /**
     * 设备名称
     * @type {string}
     * @memberof ScenarioScheduleEditFlow
     */
    deviceName?: string | null
    /**
     * 设备Id
     * @type {string}
     * @memberof ScenarioScheduleEditFlow
     */
    deviceId?: string
    /**
     * 调配水量
     * @type {number}
     * @memberof ScenarioScheduleEditFlow
     */
    flow?: number
    /**
     * 设备的流量指标的时序值
     * @type {Array<OnlineData>}
     * @memberof ScenarioScheduleEditFlow
     */
    indicatorDataTs?: Array<OnlineData> | null
    /**
     * 编辑后的调配水量
     * @type {number}
     * @memberof ScenarioScheduleEditFlow
     */
    editFlow?: number
}
