/* tslint:disable */
/* eslint-disable */
/**
 * 城市供水业务中台
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ScenarioScheduleDevice
 */
export interface ScenarioScheduleDevice {
    /**
     * 设备名称
     * @type {string}
     * @memberof ScenarioScheduleDevice
     */
    deviceName?: string | null
    /**
     * 指标名称
     * @type {Array<string>}
     * @memberof ScenarioScheduleDevice
     */
    indicators?: Array<string> | null
}
