/* tslint:disable */
/* eslint-disable */
/**
 * 城市供水业务中台
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { FenQiFlowEditInfo } from './fen-qi-flow-edit-info'
// May contain unused imports in some cases
// @ts-ignore
import { ScenarioScheduleEditFlow } from './scenario-schedule-edit-flow'
// May contain unused imports in some cases
// @ts-ignore
import { TankOpenOrCloseEditDto } from './tank-open-or-close-edit-dto'

/**
 *
 * @export
 * @interface ScenarioAllocationEditDto
 */
export interface ScenarioAllocationEditDto {
    /**
     * 方案调配水量数据（包含编辑前和编辑后的调配水量数据）
     * @type {Array<ScenarioScheduleEditFlow>}
     * @memberof ScenarioAllocationEditDto
     */
    editScenarioScheduleFlows?: Array<ScenarioScheduleEditFlow> | null
    /**
     * 分期水量数据（包含编辑前和编辑后的分期水量数据）
     * @type {Array<FenQiFlowEditInfo>}
     * @memberof ScenarioAllocationEditDto
     */
    editFenQiFlowList?: Array<FenQiFlowEditInfo> | null
    /**
     * 水库编辑数据
     * @type {Array<TankOpenOrCloseEditDto>}
     * @memberof ScenarioAllocationEditDto
     */
    tankOpenOrCloseEditInfos?: Array<TankOpenOrCloseEditDto> | null
    /**
     * 长潭水库编辑后的液位
     * @type {number}
     * @memberof ScenarioAllocationEditDto
     */
    changTanEditLevel?: number
}
