/* tslint:disable */
/* eslint-disable */
/**
 * 城市供水业务中台
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ScenarioInfo3
 */
export interface ScenarioInfo3 {
    /**
     *
     * @type {string}
     * @memberof ScenarioInfo3
     */
    name?: string | null
    /**
     *
     * @type {string}
     * @memberof ScenarioInfo3
     */
    minIOBucket?: string | null
    /**
     *
     * @type {string}
     * @memberof ScenarioInfo3
     */
    minIOPath?: string | null
    /**
     *
     * @type {string}
     * @memberof ScenarioInfo3
     */
    tenantId?: string | null
    /**
     *
     * @type {string}
     * @memberof ScenarioInfo3
     */
    version?: string | null
    /**
     *
     * @type {string}
     * @memberof ScenarioInfo3
     */
    description?: string | null
    /**
     *
     * @type {string}
     * @memberof ScenarioInfo3
     */
    state?: string | null
    /**
     *
     * @type {number}
     * @memberof ScenarioInfo3
     */
    autoAmend?: number
    /**
     *
     * @type {number}
     * @memberof ScenarioInfo3
     */
    onlineFirst?: number
    /**
     *
     * @type {number}
     * @memberof ScenarioInfo3
     */
    published?: number
    /**
     *
     * @type {number}
     * @memberof ScenarioInfo3
     */
    calculated?: number
    /**
     *
     * @type {number}
     * @memberof ScenarioInfo3
     */
    checked?: number
    /**
     *
     * @type {number}
     * @memberof ScenarioInfo3
     */
    modified?: number
    /**
     *
     * @type {number}
     * @memberof ScenarioInfo3
     */
    autoCalculate?: number
    /**
     *
     * @type {string}
     * @memberof ScenarioInfo3
     */
    createTime?: string | null
    /**
     *
     * @type {string}
     * @memberof ScenarioInfo3
     */
    endTime?: string | null
    /**
     *
     * @type {string}
     * @memberof ScenarioInfo3
     */
    startTime?: string | null
    /**
     *
     * @type {string}
     * @memberof ScenarioInfo3
     */
    currentTime?: string | null
    /**
     *
     * @type {string}
     * @memberof ScenarioInfo3
     */
    projectFile?: string | null
    /**
     *
     * @type {string}
     * @memberof ScenarioInfo3
     */
    relativeFolder?: string | null
    /**
     *
     * @type {number}
     * @memberof ScenarioInfo3
     */
    enabled?: number
    /**
     *
     * @type {number}
     * @memberof ScenarioInfo3
     */
    readOnly?: number
    /**
     *
     * @type {string}
     * @memberof ScenarioInfo3
     */
    inheritedScenario?: string
    /**
     *
     * @type {string}
     * @memberof ScenarioInfo3
     */
    id?: string
    /**
     *
     * @type {string}
     * @memberof ScenarioInfo3
     */
    scenarioCode?: string | null
    /**
     *
     * @type {string}
     * @memberof ScenarioInfo3
     */
    scenarioName?: string | null
    /**
     *
     * @type {string}
     * @memberof ScenarioInfo3
     */
    modelType?: string | null
    /**
     *
     * @type {string}
     * @memberof ScenarioInfo3
     */
    modelSubType?: string | null
    /**
     *
     * @type {number}
     * @memberof ScenarioInfo3
     */
    template?: number
}
