/* tslint:disable */
/* eslint-disable */
/**
 * 城市供水业务中台
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface TankOpenOrCloseEditDto
 */
export interface TankOpenOrCloseEditDto {
    /**
     * 水池中文名
     * @type {string}
     * @memberof TankOpenOrCloseEditDto
     */
    name?: string | null
    /**
     * 水池muid
     * @type {string}
     * @memberof TankOpenOrCloseEditDto
     */
    tankMuid?: string | null
    /**
     * 水池连接的管道muid
     * @type {string}
     * @memberof TankOpenOrCloseEditDto
     */
    pipeMuid?: string | null
    /**
     * 管道默认初始状态
     * @type {boolean}
     * @memberof TankOpenOrCloseEditDto
     */
    pipeInitStatus?: boolean
}
