export const labelConfig = {
    searchHolder: '搜索',
    checkedNormal: '正常',
    checkedDeal: '已处理',
    calcText: '计算',
    cancelText: '取消', // 取消计算
    editText: '编辑',
    deleteText: '删除',
    logText: '日志',
    logTitle: '模型计算日志',
    noLogTip: '暂无日志',
    upload: '上传',
    download: '下载',
    submitText: '配置',
    compareText: '方案对比',
    confirmDeleteText: '确认删除该方案吗？',
    setCurrentText: '设为当前',
    currentText: '当前',
    editScenarioText: '方案列表',
    editBreadName: '编辑方案',
    newBreadName: '新建方案',
    // 添加方案
    addScenarioText: '添加方案',
    editNewScenarioText: '方案名称',
    nameTip: '请填写方案名称',
    editNewScenarioDescription: '方案描述',
    descriptionTip: '请填写方案描述',
    scenarioDateText: '方案日期',
    dataGovernanceText: '数据治理',
    loadingText: '加载中...',
    loadingNoneDataText: '暂无数据',
    assetFlowType: '流量计',
    assetEvaluationType: '考核表',
    assetStationType: '厂站',
    submitCommitText: '厂站数据缺失，请上传厂站数据，否则系统将自动补齐。',
    cancelCommitText:
        '方案修改未保存，选择确定则不修改/新增方案退出至方案列表，选择取消，退至编辑界面',
    cancelCommitNormalText: '确定取消吗?',
    dataStationUploadedText: '用户已上传厂站数据',
    dataStationNotUploadText: '用户未上传厂站数据',
    // 关阀方案
    labelValveTimeRange: '关阀时段选择',
    labelValvePipeTableTitle: '已选择管道',
    labelBtnSelectPipe: '选择管道',
    labelBtnQueryValve: '查询阀门',
    labelValveTableTitle: '需要关闭的阀门',
    LabelAddSubText: '添加',
    LabelValveSubNewBreadName: '新建关阀调度方案',
    LabelValveSubEditBreadName: '编辑关阀调度方案',
    LabelValveSubTablePressureTitle: '出口压力调度',
    LabelValveSubChartPressureTitle: '出口压力展示',
    LabelValveViewDetailsTitle: '查看结果',
    dataScheduleNotUploadedText: '用户未上传调度方案',
    dataScheduleUploadedText: '用户已上传调度方案',

    // 统计分析
    LabelValveStatisticsAnalysisTitle: '统计分析',
}
