export const BASE_PRESSURE = 'BASE_PRESSURE'
export const BASE_PIPE = 'BASE_PIPE'
export const BASE_JUNCTION = 'BASE_JUNCTION'
export const BASE_TANK = 'BASE_TANK'
export const BASE_VALVE = 'BASE_VALVE'
export const BASE_PUMP = 'BASE_PUMP'
export const BASE_DEVICE = 'BASE_DEVICE'
export const BASE_DEVICE_PRESSURE = 'BASE_DEVICE_PRESSURE'
export const BASE_DEVICE_EVALUATION = 'BASE_DEVICE_EVALUATION'
export const BASE_DEVICE_FACTORY = 'BASE_DEVICE_FACTORY'
export const BASE_DEVICE_FLOW = 'BASE_DEVICE_FLOW'
export const BASE_HIGHLIGHT_PIPE = 'BASE_HIGHLIGHT_PIPE'
export const BASE_CLOSING_VALVE = 'BASE_CLOSING_VALVE'
export const BASE_DMA = 'BASE_DMA'
export const BASE_CUT_OFF_WATER = 'BASE_CUT_OFF_WATER'
export const REPAIR_PIPE = 'REPAIR_PIPE' // 抢修管理pipe图层
export const REPAIR_JUNCTION = 'REPAIR_JUNCTION' // 抢修标记图层
export const REPAIR_TEMP_JUNCTION = 'REPAIR_TEMP_JUNCTION' // 抢修标记临时图层图层

export const BASE_RIVER = 'BASE_RIVER'
export const BASE_MESH = 'BASE_MESH'
export const BASE_GATE = 'BASE_GATE'
export const MAP_RESULT = 'MapResult'

export const MODEL_JUNCTION = 'MODEL_JUNCTION'
export const MODEL_PIPE = 'MODEL_PIPE'
export const MODEL_PUMP = 'MODEL_PUMP'
export const MODEL_TANK = 'MODEL_TANK'
export const MODEL_VALVE = 'MODEL_VALVE'
export const MODEL_DEVICE = 'MODEL_DEVICE'
export const MODEL_DMA = 'MODEL_DMA'

export const MODEL_RIVER = 'MODEL_RIVER'
export const MODEL_MESH = 'MODEL_MESH'

export const CLOSED_VALVE = 'CLOSED_VALVE'
export const BURST_PIPE = 'BURST_PIPE'
export const POLLUTANT = 'POLLUTANT'

export const YZ_RIVER = 'YZ_RIVER'
export const ANIMATION_POINT = 'ANIMATION_POINT'

// * 20220530 新增压力、流量、余氯

/** 长治 */
export const BASE_SECTION_EXAM = 'BASE_SECTION_EXAM'
export const BASE_SEWAGE_PLANT = 'BASE_SEWAGE_PLANT'
export const BASE_INDUSTRIAL_ENTERPRISE = 'BASE_INDUSTRIAL_ENTERPRISE'
export const BASE_RAIN_GAUGE = 'BASE_RAIN_GAUGE'
export const BASE_RESERVOIR = 'BASE_RESERVOIR'
export const BASE_HYDROLOGICAL_STATION = 'BASE_HYDROLOGICAL_STATION'
export const BASE_DRAINAGE_BASIN = 'BASE_DRAINAGE_BASIN'
export const BASE_DISTRICT = 'BASE_DISTRICT'
// export const BASE_WATER_SOURCE = 'BASE_WATER_SOURCE'
export const BASE_POLYGON = 'BASE_POLYGON '
