export const MODEL_PREFIX = 'MODEL_'
export const BASE_PREFIX = `BASE_`

export const BASE_PIPE = `${BASE_PREFIX}PIPE`
export const BASE_JUNCTION = `${BASE_PREFIX}JUNCTION`
export const BASE_RIVER = `${BASE_PREFIX}RIVER`
export const BASE_PUMP = `${BASE_PREFIX}PUMP`
export const BASE_GATE = `${BASE_PREFIX}GATE`
export const BASE_MANHOLE = `${BASE_PREFIX}MANHOLE`
export const BASE_SENSITIVE_POINT = `${BASE_PREFIX}SENSITIVE_POINT` // 易涝点

export const MODEL_PIPE = `${MODEL_PREFIX}PIPE`
export const MODEL_MESH = `${MODEL_PREFIX}MESH`
export const MODEL_JUNCTION = `${MODEL_PREFIX}JUNCTION`

export const ANIMATION_POINT = `ANIMATION_POINT`
