on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
          with:
            version: 8.6.7
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
          cache-dependency-path: /home/runner/work/ningbo-wd-webapp/ningbo-wd-webapp/common/config/pnpm-lock.yaml
      
      - name: Cache pnpm modules
        id: cache-pnpm
        uses: actions/cache@v3
        with:
          path: /home/runner/work/ningbo-wd-webapp/ningbo-wd-webapp/common/config/pnpm-lock.yaml
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Setup pnpm
        if: steps.cache-pnpm.outputs.cache-hit != 'true'
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: rush install
        run: 'node common/scripts/install-run-rush.js install --to "dhi-dss-ningbo-wd-webapp" --debug-package-manager --max-install-attempts 3'

      - name: rush build
        run: 'export NODE_OPTIONS=--max_old_space_size=8192 && node common/scripts/install-run-rush.js build --verbose -t "dhi-dss-ningbo-wd-webapp"'
    
      - name: Archive production files
        run: |
          mkdir release
          zip -r release/app.zip App/NingBoWDWebApp/dist/* # 假设你的构建产物在dist目录下，根据实际情况调整
        shell: bash
      
      - name: Create a Release
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          tag: $GITHUB_SHA
          token: ${{ secrets.RELEASE_TOKEN }}
          removeArtifacts: true


      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # 这是从create_release步骤获取的URL
          asset_path: ./release/app.zip
          asset_name: app.zip
          asset_content_type: application/zip