on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    outputs:
      build_id: ${{ steps.build_step.outputs.build_id }}

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8.6.7
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
          cache-dependency-path: common/config/rush/pnpm-lock.yaml
      
      - name: rush install
        run: 'node common/scripts/install-run-rush.js install --to "dhi-dss-ningbo-wd-webapp" --debug-package-manager --max-install-attempts 3'

      - name: rush build
        run: 'export NODE_OPTIONS=--max_old_space_size=8192 && node common/scripts/install-run-rush.js build --verbose -t "dhi-dss-ningbo-wd-webapp"'
    
      - name: create build id
        id: build_step
        run: echo "build_id=$RANDOM" >> $GITHUB_OUTPUT

  deploy:  
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Start deploy
        run: echo "Deploying build ${{ needs.build.outputs.build_id }}"
      
      - name: Archive production files
        run: |
          mkdir release
          zip -r release/app.zip App/NingBoWDWebApp/dist/* # 假设你的构建产物在dist目录下，根据实际情况调整
        shell: bash
      
      - name: Create a Release
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          artifacts: ./release/app.zip
          tag: ${{ needs.build.outputs.build_id }}
          token: ${{ secrets.RELEASE_TOKEN }}
          removeArtifacts: true
